export const REQUEST_REGISTER_USER = 'REQUEST_REGISTER_USER';
export const RECEIVE_REGISTER_USER = 'RECEIVE_REGISTER_USER';
export const REQUEST_LOGIN = 'REQUEST_LOGIN';
export const RECEIVE_LOGIN = 'RECEIVE_LOGIN';
export const LOGOUT = 'LOGOUT';
export const REQUEST_LOGIN_USING_TOKEN = 'REQUEST_LOGIN_USING_TOKEN';
export const RECEIVE_LOGIN_USING_TOKEN = 'RECEIVE_LOGIN_USING_TOKEN';