version: '2'
services:
  server:
    build: ./server
    ports:
      - "8888:80"
    volumes:
      - /workspace/browser-game/server/slim-project:/var/www/html
    links:
      - db
  db:
    build: ./db
    ports:
      - "3306"
    volumes:
      - /workspace/browser-game/db/data:/var/lib/mysql
      - /workspace/browser-game/db/initdb.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: browser_game
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root_password
  client:
    build: ./client
    ports:
      - "8080:3000"
    volumes:
      - /workspace/browser-game/client:/app
      - /app/react-app/node_modules
    tty: true

