version: '2'
services:
  server:
    build: ./server
    ports:
      - "8888:80"
    volumes:
      - ./server/src:/var/www/html
    links:
      - db
  db:
    build: ./db
    ports:
      - "3306"
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/initdb.d:/docker-entrypoint-initdb.d
      - ./db/conf.d:/etc/mysql/conf.d
    environment:
      MYSQL_DATABASE: browser_game
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root_password
  client:
    build: ./client
    ports:
      - "8080:3000"
    volumes:
      - ./client:/app
    tty: true

